class UI:
    BACK_ARROW = "⤴️"
    FORWARD_ARROW = "▶️"
    BACKWARD_ARROW = "◀️"

    CHECK_MARK = "✅"
    CROSS_MARK = "❌"
    WARNING = "⚠️"
    INFO = "ℹ️"

    WORKOUT = "🏋️"
    LOCATION = "📍"
    CALENDAR = "📅"
    CLOCK = "⏰"
    MONEY = "💰"
    COMMENT = "📝"
    PERSON = "👤"
    PEOPLE = "👥"
    CHART = "📊"
    PLUS = "➕"
    SKIP = "⏭️"
    GEAR = "🔧"
    STAR = "⭐"
    LOCK = "🔒"
    GLOBE = "🌐"

    BACK_TO_PANEL = f"{BACK_ARROW} Назад в панель"
    BACK_TO_LIST = f"{BACK_ARROW} Назад к списку"
    CONFIRM = f"{CHECK_MARK} Подтвердить"
    CANCEL = f"{CROSS_MARK} Отменить"
    SELECT_LOCATION = f"{LOCATION} Отправить геолокацию"
    SKIP_STEP = f"{SKIP} Пропустить"
    EDIT = "✏️ Изменить"
    DELETE = "🗑️ Удалить"
    REPORT = f"{CHART} Отчеты"
    CREATE_WORKOUT = f"{PLUS} Создать тренировку"
    LIST_USERS = f"{PEOPLE} Список пользователей"
    PUBLIC_WORKOUT = f"{GLOBE} Публичная (рассылка всем)"
    PRIVATE_WORKOUT = f"{LOCK} Приватная (выбор пользователей)"